# Target with dependencies and the binaries to run the complete flow
FROM openroad/flow-runtime

WORKDIR /OpenROAD-flow-scripts

# synthesis tools binaries and plugins
COPY --from=openroad/yosys /install ./tools/install/yosys
COPY --from=openroad/lsoracle /LSOracle/build/core/lsoracle ./tools/install/LSOracle/bin/lsoracle
COPY --from=openroad/lsoracle /LSOracle/core/test.ini ./tools/install/LSOracle/share/lsoracle/test.ini
COPY --from=openroad/lsoracle /LSOracle/build/yosys-plugin/oracle.so /OpenROAD-flow/tools/install/yosys/share/yosys/plugin/oracle.so

# openroad binary
COPY --from=openroad/centos7-builder-gcc /OpenROAD/build/src/openroad ./tools/install/OpenROAD/bin/openroad

# flow files
COPY ./setup_env.sh .
#COPY ./flow ./flow

# avoid issues with permissions
#RUN chmod o+rw -R /OpenROAD-flow-scripts

RUN yum install -y gperftools-libs
COPY --from=stevenmburns/yosys-systemverilog-runtime /image ./tools/install/image
